// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy6VqE2TNmMf_7a-UrKiISOHZpfwEQhD0',
    appId: '1:295342396839:android:d64e3778106d62330d5282',
    messagingSenderId: '295342396839',
    projectId: 'hari-smruti',
    storageBucket: 'hari-smruti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKjoKWgL88S8ahvwQd2QA6bPSU6pGija8',
    appId: '1:295342396839:ios:cf1f9ba8f91ab6bd0d5282',
    messagingSenderId: '295342396839',
    projectId: 'hari-smruti',
    storageBucket: 'hari-smruti.firebasestorage.app',
    iosBundleId: 'org.hp.harismrutihp',
  );
}
